### ISSUE TITLE
Biblatex name format changes in version >= 3.3

### ISSUE THREAD

**Issue by moewew** [ienissei/frenchlaw#40]
Please excuse me not writing in French.

Since I happened to come across this project a while ago, I hope you don't mind me giving you a heads-up about recent changes in biblatex and its name formatting system. If you already know about this, please forgive my impertinence. 

The release notes http://mirrors.ctan.org/macros/latex/contrib/biblatex/RELEASE give a short overview over the changes. Most importantly `\DeclareNameFormat` has a drastically different syntax (which will change a bit in [3.4](https://github.com/plk/biblatex/releases/tag/v3.4)), the standard name formats accessible with `\DeclareNameAlias` have been renamed, so have the `name:...` macros and `\mkbibnamelast` is replaced by `\mkbibnamefamily` (same for `\mkbibnamefirst` of course). `\DeclareNameAlias{author}{last-first/first-last}` would be `\DeclareNameAlias{author}{family-given/given-family}` under the new scheme.

For backwards compatibility you could use `\@ifpackagelater{biblatex}{2016/03/03}` (which actually checks that the package is not older than 2016/03/03).

**Comment by ienissei** [comment]
Thank you kindly for the update about biblatex. I will implement it whenever time allows (my issues list keeps to be ever growing).
